In [ ]:
import torch
# Pick a random vector
z = torch.rand((2, 3))
z

tensor([[0.2279, 0.2471, 0.7297],
        [0.1047, 0.2904, 0.1499]])

In [ ]:
# Permutation of tensor
torch.einsum('ij -> ji', z)

tensor([[0.2279, 0.1047],
        [0.2471, 0.2904],
        [0.7297, 0.1499]])

In [ ]:
# Summation of tensor
torch.einsum('ij -> ', z)

tensor(1.7498)

In [ ]:
# Sum columnwise
torch.einsum('ij -> j', z)

tensor([0.3327, 0.5375, 0.8796])

In [ ]:
# Sum rowwise
torch.einsum('ij -> i', z)

tensor([1.2047, 0.5450])

In [ ]:
# Matrix Vector multiplication
y = torch.rand((1, 3))
torch.einsum('ik, jk -> ij', z, y)

tensor([[0.3799],
        [0.1832]])

In [ ]:
# Matrix-Matrix multiplication
torch.einsum('ik, jk -> ij', z, z)

tensor([[0.6455, 0.2050],
        [0.2050, 0.1178]])

In [ ]:
# Dot product of first row of matrix - Product and Sum em' up
torch.einsum('i,i -> ', z[0], z[0])

tensor(0.6455)

In [ ]:
# Matrix dot product
torch.einsum('ij, ij -> ', z, z)

tensor(0.7633)

In [ ]:
# Hadamard product
torch.einsum('ij, ij -> ij', z, z)

tensor([[0.0519, 0.0610, 0.5325],
        [0.0110, 0.0843, 0.0225]])

In [ ]:
# Outer product 
x = torch.rand((3))
y = torch.rand((5)) #Vectors
torch.einsum('i,j -> ij', x, y)

tensor([[0.4602, 0.6050, 0.1469, 0.5623, 0.5378],
        [0.3053, 0.4014, 0.0975, 0.3731, 0.3568],
        [0.0105, 0.0139, 0.0034, 0.0129, 0.0123]])

In [ ]:
# Batch matrix multiplication (BMM)
x = torch.rand((2, 3, 5))
y = torch.rand((2, 5, 4))
torch.einsum('ijk, ikl -> ijl', x, y)

tensor([[[0.7460, 0.5306, 1.0423, 1.0586],
         [1.4315, 1.0697, 1.3454, 1.4614],
         [0.9488, 0.5936, 1.3178, 1.4932]],

        [[1.5799, 1.0235, 0.7281, 1.2465],
         [1.6954, 1.1087, 0.6215, 1.4870],
         [1.0122, 0.9348, 0.5714, 1.1257]]])

In [ ]:
# Finding the trace of a matrix
z = torch.rand((3, 3))
print(z)
y = torch.einsum('ii->', z)
print(y)

tensor([[0.3781, 0.7971, 0.3055],
        [0.7768, 0.9433, 0.6507],
        [0.1399, 0.8613, 0.4970]])
tensor(1.8184)


In [ ]:
# Getting the diagonal of a matrix
torch.einsum('ii->i', z)

tensor([0.3781, 0.9433, 0.4970])